services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db

    environment:
      MYSQL_DATABASE: nst2025
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend
    container_name: spring_backend

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nst2025?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_LIQUIBASE_URL: jdbc:mysql://mysql:3306/nst2025?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: root

    ports:
      - "8080:8080"

  frontend:
    build: ./Frontend
    container_name: react_frontend

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  mysql_data:
